services:
  postgres-clientes:
    image: postgres:15
    container_name: clientes-db
    environment:
      POSTGRES_DB: clientesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clientesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-cuentas:
    image: postgres:15
    container_name: cuentas-db
    environment:
      POSTGRES_DB: cuentasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cuentasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  clientes-service:
    build: ./clientes-service
    ports:
      - "8081:8081"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres-clientes:
        condition: service_healthy

  cuentas-service:
    build: ./cuentas-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cuentas:5432/cuentasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
       postgres-cuentas:
        condition: service_healthy